# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/tejasri3657/31d566b2715e33512f8dbc3fd7c1447c/copy-of-assignment1.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

#import math
#from coeffs import *
import subprocess
import shlex


#generating the line points
def line_gen(A,B):
	len = 20
	dim = A.shape[0]
	x_AB = np.zeros((dim,len))
	lam_1 = np.linspace(0,1,len)
	for i in range(len):
		temp1 = A + lam_1[i]*(B-A)
		x_AB[:,i]=temp1.T
	return x_AB

#vertices
B = np.array([-1.5,6.5])
C= np.array([0,0])
A = np.array([6.5, 0])


#Direction vectors
print(B-C, C-A, A-B)

#Side lengths
print(LA.norm(B-C), LA.norm(C-A), LA.norm(A-B))


#Generating the lines
x_BC = line_gen(B,C)
x_CA = line_gen(C,A)
x_AB = line_gen(A,B)



#plotting the all lines
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CA[0,:],x_CA[1,:],label='$CA$')
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')



plt.plot(B[0],B[1],'o')
plt.text(B[0]*(1+0.3), B[1]*(1), 'B')
plt.plot(C[0],C[1],'o')
plt.text(C[0]*(1+0.1), C[1]*(1), 'C')
plt.plot(A[0], A[1], 'o')
plt.text(A[0]*(1+0.2), A[1]*(1),'A')


#angle C=110°
import math
print(C)


plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid()
plt.axis('equal')

#Saving figures
#if using termux
plt.savefig('isosceles triangle.pdf')
#else
plt.show()



